apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base

patches:
- path: ingress-prod.yaml
images:
- name: mazurlinux/backend
  newName: mazurlinux/backend
  newTag: 244f0d1d3e43a3d75f6188d07c97a21bfd70c4ed
- name: mazurlinux/frontend
  newName: mazurlinux/frontend
  newTag: 244f0d1d3e43a3d75f6188d07c97a21bfd70c4ed
