apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base

patches:
- path: ingress-prod.yaml
images:
- name: mazurlinux/backend
  newName: mazurlinux/backend
  newTag: 1a98cf283bbc93d4bf7172b49778410660fc4fff
- name: mazurlinux/frontend
  newName: mazurlinux/frontend
  newTag: 1a98cf283bbc93d4bf7172b49778410660fc4fff
