apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base

patches:
- path: ingress-prod.yaml
images:
- name: mazurlinux/backend
  newName: mazurlinux/backend
  newTag: de72f43ec17b047be19b5cd4950642f3c1546118
- name: mazurlinux/frontend
  newName: mazurlinux/frontend
  newTag: de72f43ec17b047be19b5cd4950642f3c1546118
