apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
- ../../base

patches:
- path: ingress-dev.yaml
images:
- name: mazurlinux/backend
  newName: mazurlinux/backend
  newTag: fe846cfa08b458d6b1f7fb516ec7045fd2eaca57
- name: mazurlinux/frontend
  newName: mazurlinux/frontend
  newTag: fe846cfa08b458d6b1f7fb516ec7045fd2eaca57
