apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
- ../../base

patches:
- path: ingress-dev.yaml
images:
- name: mazurlinux/backend
  newName: mazurlinux/backend
  newTag: f04ebe6ba41d03119c62ea6b62da6037ccfcc5db
- name: mazurlinux/frontend
  newName: mazurlinux/frontend
  newTag: f04ebe6ba41d03119c62ea6b62da6037ccfcc5db
