apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
- ../../base

patches:
- path: ingress-dev.yaml
images:
- name: mazurlinux/backend
  newName: mazurlinux/backend
  newTag: 4ac1bbb61838d18f50506b0a678a12130cf7a7b6
- name: mazurlinux/frontend
  newName: mazurlinux/frontend
  newTag: 4ac1bbb61838d18f50506b0a678a12130cf7a7b6
